# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manageprojects.ui'
#
# Created: Mon Apr 26 22:07:15 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ManageProjects(object):
    def setupUi(self, ManageProjects):
        ManageProjects.setObjectName("ManageProjects")
        ManageProjects.resize(869, 526)
        self.centralwidget = QtGui.QWidget(ManageProjects)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.projectsFrame = QtGui.QFrame(self.centralwidget)
        self.projectsFrame.setMaximumSize(QtCore.QSize(160, 16777215))
        self.projectsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.projectsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.projectsFrame.setObjectName("projectsFrame")
        self.verticalLayout = QtGui.QVBoxLayout(self.projectsFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.projectsFrame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.projectslist = QtGui.QListWidget(self.projectsFrame)
        self.projectslist.setTabKeyNavigation(True)
        self.projectslist.setViewMode(QtGui.QListView.ListMode)
        self.projectslist.setObjectName("projectslist")
        self.verticalLayout.addWidget(self.projectslist)
        self.newProject = QtGui.QLineEdit(self.projectsFrame)
        self.newProject.setObjectName("newProject")
        self.verticalLayout.addWidget(self.newProject)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.projectCreate = QtGui.QPushButton(self.projectsFrame)
        self.projectCreate.setMaximumSize(QtCore.QSize(50, 16777215))
        self.projectCreate.setObjectName("projectCreate")
        self.horizontalLayout_2.addWidget(self.projectCreate)
        self.projectDelete = QtGui.QPushButton(self.projectsFrame)
        self.projectDelete.setMaximumSize(QtCore.QSize(50, 16777215))
        self.projectDelete.setObjectName("projectDelete")
        self.horizontalLayout_2.addWidget(self.projectDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_18.addWidget(self.projectsFrame)
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setMinimumSize(QtCore.QSize(300, 0))
        self.tabs.setObjectName("tabs")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sdfdfg = QtGui.QWidget(self.tab_5)
        self.sdfdfg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.sdfdfg.setObjectName("sdfdfg")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.sdfdfg)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.sdfdfg)
        self.label_2.setMinimumSize(QtCore.QSize(300, 50))
        self.label_2.setMaximumSize(QtCore.QSize(300, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/banner/banner.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.sdfdfg)
        self.line = QtGui.QFrame(self.tab_5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.projectName = QtGui.QLabel(self.tab_5)
        self.projectName.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.projectName.setFont(font)
        self.projectName.setAlignment(QtCore.Qt.AlignCenter)
        self.projectName.setObjectName("projectName")
        self.verticalLayout_2.addWidget(self.projectName)
        self.horizontalGroupBox = QtGui.QGroupBox(self.tab_5)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.projectStatistics = QtGui.QLabel(self.horizontalGroupBox)
        self.projectStatistics.setObjectName("projectStatistics")
        self.horizontalLayout_14.addWidget(self.projectStatistics)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox)
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.projectJobsStatistics = QtGui.QLabel(self.groupBox)
        self.projectJobsStatistics.setObjectName("projectJobsStatistics")
        self.horizontalLayout_15.addWidget(self.projectJobsStatistics)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.tabs.addTab(self.tab_5, "")
        self.tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.docslist = QtGui.QListWidget(self.tab)
        self.docslist.setMaximumSize(QtCore.QSize(150, 16777215))
        self.docslist.setObjectName("docslist")
        self.verticalLayout_3.addWidget(self.docslist)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.docCreate = QtGui.QPushButton(self.tab)
        self.docCreate.setMaximumSize(QtCore.QSize(50, 16777215))
        self.docCreate.setObjectName("docCreate")
        self.horizontalLayout_3.addWidget(self.docCreate)
        self.docDelete = QtGui.QPushButton(self.tab)
        self.docDelete.setMaximumSize(QtCore.QSize(50, 16777215))
        self.docDelete.setObjectName("docDelete")
        self.horizontalLayout_3.addWidget(self.docDelete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.doctext = QtGui.QTextEdit(self.tab)
        self.doctext.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.doctext.setObjectName("doctext")
        self.verticalLayout_4.addWidget(self.doctext)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.docOpen = QtGui.QPushButton(self.tab)
        self.docOpen.setObjectName("docOpen")
        self.horizontalLayout_4.addWidget(self.docOpen)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.noteslist = QtGui.QListWidget(self.tab_2)
        self.noteslist.setMaximumSize(QtCore.QSize(150, 16777215))
        self.noteslist.setObjectName("noteslist")
        self.verticalLayout_5.addWidget(self.noteslist)
        self.newnote = QtGui.QLineEdit(self.tab_2)
        self.newnote.setMaximumSize(QtCore.QSize(150, 16777215))
        self.newnote.setObjectName("newnote")
        self.verticalLayout_5.addWidget(self.newnote)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.noteCreate = QtGui.QPushButton(self.tab_2)
        self.noteCreate.setMaximumSize(QtCore.QSize(50, 16777215))
        self.noteCreate.setObjectName("noteCreate")
        self.horizontalLayout_5.addWidget(self.noteCreate)
        self.noteDelete = QtGui.QPushButton(self.tab_2)
        self.noteDelete.setMaximumSize(QtCore.QSize(50, 16777215))
        self.noteDelete.setObjectName("noteDelete")
        self.horizontalLayout_5.addWidget(self.noteDelete)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.notetext = QtGui.QTextEdit(self.tab_2)
        self.notetext.setObjectName("notetext")
        self.verticalLayout_6.addWidget(self.notetext)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.noteSave = QtGui.QPushButton(self.tab_2)
        self.noteSave.setObjectName("noteSave")
        self.horizontalLayout_6.addWidget(self.noteSave)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.tabs.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.linkslist = QtGui.QTreeWidget(self.tab_3)
        self.linkslist.setIndentation(0)
        self.linkslist.setAnimated(True)
        self.linkslist.setObjectName("linkslist")
        item_0 = QtGui.QTreeWidgetItem(self.linkslist)
        self.verticalLayout_7.addWidget(self.linkslist)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.linkUrl = QtGui.QLineEdit(self.tab_3)
        self.linkUrl.setMaximumSize(QtCore.QSize(120, 16777215))
        self.linkUrl.setObjectName("linkUrl")
        self.horizontalLayout_8.addWidget(self.linkUrl)
        self.linkDesc = QtGui.QLineEdit(self.tab_3)
        self.linkDesc.setObjectName("linkDesc")
        self.horizontalLayout_8.addWidget(self.linkDesc)
        self.linkDescGet = QtGui.QPushButton(self.tab_3)
        self.linkDescGet.setObjectName("linkDescGet")
        self.horizontalLayout_8.addWidget(self.linkDescGet)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.linkCreate = QtGui.QPushButton(self.tab_3)
        self.linkCreate.setObjectName("linkCreate")
        self.horizontalLayout_9.addWidget(self.linkCreate)
        self.linkDelete = QtGui.QPushButton(self.tab_3)
        self.linkDelete.setObjectName("linkDelete")
        self.horizontalLayout_9.addWidget(self.linkDelete)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.tabs.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.jobslist = QtGui.QTreeWidget(self.tab_4)
        self.jobslist.setIndentation(0)
        self.jobslist.setAnimated(True)
        self.jobslist.setObjectName("jobslist")
        self.verticalLayout_8.addWidget(self.jobslist)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.jobName = QtGui.QLineEdit(self.tab_4)
        self.jobName.setObjectName("jobName")
        self.horizontalLayout_10.addWidget(self.jobName)
        self.jobTimeCheck = QtGui.QCheckBox(self.tab_4)
        self.jobTimeCheck.setMaximumSize(QtCore.QSize(18, 16777215))
        self.jobTimeCheck.setText("")
        self.jobTimeCheck.setCheckable(True)
        self.jobTimeCheck.setTristate(False)
        self.jobTimeCheck.setObjectName("jobTimeCheck")
        self.horizontalLayout_10.addWidget(self.jobTimeCheck)
        self.jobTime = QtGui.QDateTimeEdit(self.tab_4)
        self.jobTime.setEnabled(False)
        self.jobTime.setMinimumSize(QtCore.QSize(130, 0))
        self.jobTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.jobTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.jobTime.setCalendarPopup(False)
        self.jobTime.setObjectName("jobTime")
        self.horizontalLayout_10.addWidget(self.jobTime)
        self.jobStatus = QtGui.QComboBox(self.tab_4)
        self.jobStatus.setMinimumSize(QtCore.QSize(92, 0))
        self.jobStatus.setObjectName("jobStatus")
        self.jobStatus.addItem("")
        self.jobStatus.addItem("")
        self.jobStatus.addItem("")
        self.horizontalLayout_10.addWidget(self.jobStatus)
        self.jobCreate = QtGui.QPushButton(self.tab_4)
        self.jobCreate.setMinimumSize(QtCore.QSize(85, 0))
        self.jobCreate.setObjectName("jobCreate")
        self.horizontalLayout_10.addWidget(self.jobCreate)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.jobEditStatus = QtGui.QComboBox(self.tab_4)
        self.jobEditStatus.setMinimumSize(QtCore.QSize(92, 0))
        self.jobEditStatus.setObjectName("jobEditStatus")
        self.jobEditStatus.addItem("")
        self.jobEditStatus.addItem("")
        self.jobEditStatus.addItem("")
        self.horizontalLayout_11.addWidget(self.jobEditStatus)
        self.jobEdit = QtGui.QPushButton(self.tab_4)
        self.jobEdit.setMinimumSize(QtCore.QSize(85, 0))
        self.jobEdit.setObjectName("jobEdit")
        self.horizontalLayout_11.addWidget(self.jobEdit)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.jobDelete = QtGui.QPushButton(self.tab_4)
        self.jobDelete.setMinimumSize(QtCore.QSize(85, 0))
        self.jobDelete.setObjectName("jobDelete")
        self.horizontalLayout_11.addWidget(self.jobDelete)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.jobNotes = QtGui.QComboBox(self.tab_4)
        self.jobNotes.setObjectName("jobNotes")
        self.jobNotes.addItem("")
        self.horizontalLayout_12.addWidget(self.jobNotes)
        self.jobAssignNote = QtGui.QPushButton(self.tab_4)
        self.jobAssignNote.setObjectName("jobAssignNote")
        self.horizontalLayout_12.addWidget(self.jobAssignNote)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.jobAddToTodays = QtGui.QPushButton(self.tab_4)
        self.jobAddToTodays.setObjectName("jobAddToTodays")
        self.horizontalLayout_12.addWidget(self.jobAddToTodays)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.tabs.addTab(self.tab_4, "")
        self.horizontalLayout_18.addWidget(self.tabs)
        self.todaysFrame = QtGui.QFrame(self.centralwidget)
        self.todaysFrame.setMinimumSize(QtCore.QSize(350, 0))
        self.todaysFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.todaysFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.todaysFrame.setObjectName("todaysFrame")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.todaysFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtGui.QLabel(self.todaysFrame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.todaysJobsList = QtGui.QTreeWidget(self.todaysFrame)
        self.todaysJobsList.setIndentation(0)
        self.todaysJobsList.setObjectName("todaysJobsList")
        self.todaysJobsList.headerItem().setText(1, "Job")
        self.verticalLayout_9.addWidget(self.todaysJobsList)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.todaysNew = QtGui.QPushButton(self.todaysFrame)
        self.todaysNew.setObjectName("todaysNew")
        self.horizontalLayout_17.addWidget(self.todaysNew)
        self.todaysInprogress = QtGui.QPushButton(self.todaysFrame)
        self.todaysInprogress.setObjectName("todaysInprogress")
        self.horizontalLayout_17.addWidget(self.todaysInprogress)
        self.todaysDone = QtGui.QPushButton(self.todaysFrame)
        self.todaysDone.setObjectName("todaysDone")
        self.horizontalLayout_17.addWidget(self.todaysDone)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.todaysDelete = QtGui.QPushButton(self.todaysFrame)
        self.todaysDelete.setMinimumSize(QtCore.QSize(100, 0))
        self.todaysDelete.setObjectName("todaysDelete")
        self.horizontalLayout_19.addWidget(self.todaysDelete)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18.addWidget(self.todaysFrame)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.op1 = QtGui.QPushButton(self.centralwidget)
        self.op1.setCheckable(True)
        self.op1.setChecked(True)
        self.op1.setObjectName("op1")
        self.horizontalLayout_16.addWidget(self.op1)
        self.op2 = QtGui.QPushButton(self.centralwidget)
        self.op2.setEnabled(False)
        self.op2.setCheckable(True)
        self.op2.setChecked(True)
        self.op2.setObjectName("op2")
        self.horizontalLayout_16.addWidget(self.op2)
        self.op3 = QtGui.QPushButton(self.centralwidget)
        self.op3.setCheckable(True)
        self.op3.setObjectName("op3")
        self.horizontalLayout_16.addWidget(self.op3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        ManageProjects.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ManageProjects)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuDocument = QtGui.QMenu(self.menubar)
        self.menuDocument.setObjectName("menuDocument")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ManageProjects.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(ManageProjects)
        self.statusBar.setObjectName("statusBar")
        ManageProjects.setStatusBar(self.statusBar)
        self.actionChange_collection = QtGui.QAction(ManageProjects)
        self.actionChange_collection.setObjectName("actionChange_collection")
        self.actionExit = QtGui.QAction(ManageProjects)
        self.actionExit.setObjectName("actionExit")
        self.actionDelete_selected_project = QtGui.QAction(ManageProjects)
        self.actionDelete_selected_project.setObjectName("actionDelete_selected_project")
        self.actionDelete_all_projects = QtGui.QAction(ManageProjects)
        self.actionDelete_all_projects.setObjectName("actionDelete_all_projects")
        self.actionCreate_new_project = QtGui.QAction(ManageProjects)
        self.actionCreate_new_project.setObjectName("actionCreate_new_project")
        self.actionClear_all_project_childs = QtGui.QAction(ManageProjects)
        self.actionClear_all_project_childs.setObjectName("actionClear_all_project_childs")
        self.actionAbout = QtGui.QAction(ManageProjects)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionChange_collection)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuProject.addAction(self.actionDelete_selected_project)
        self.menuProject.addAction(self.actionDelete_all_projects)
        self.menuProject.addAction(self.actionCreate_new_project)
        self.menuProject.addAction(self.actionClear_all_project_childs)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuDocument.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ManageProjects)
        self.tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(ManageProjects)

    def retranslateUi(self, ManageProjects):
        ManageProjects.setWindowTitle(QtGui.QApplication.translate("ManageProjects", "LadyBug Project Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ManageProjects", "Projects List:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectslist.setSortingEnabled(True)
        self.projectCreate.setText(QtGui.QApplication.translate("ManageProjects", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.projectDelete.setText(QtGui.QApplication.translate("ManageProjects", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.projectName.setText(QtGui.QApplication.translate("ManageProjects", "No project selected", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalGroupBox.setTitle(QtGui.QApplication.translate("ManageProjects", "Statistics:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectStatistics.setText(QtGui.QApplication.translate("ManageProjects", "Documents: \n"
"Notes:\n"
"Links:\n"
"Jobs:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ManageProjects", "Jobs detailed statistics:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectJobsStatistics.setText(QtGui.QApplication.translate("ManageProjects", "New:\n"
"In progress:\n"
"Done:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_5), QtGui.QApplication.translate("ManageProjects", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.docslist.setSortingEnabled(True)
        self.docCreate.setText(QtGui.QApplication.translate("ManageProjects", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.docDelete.setText(QtGui.QApplication.translate("ManageProjects", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.doctext.setHtml(QtGui.QApplication.translate("ManageProjects", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.docOpen.setText(QtGui.QApplication.translate("ManageProjects", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), QtGui.QApplication.translate("ManageProjects", "Documents", None, QtGui.QApplication.UnicodeUTF8))
        self.noteslist.setSortingEnabled(True)
        self.noteCreate.setText(QtGui.QApplication.translate("ManageProjects", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.noteDelete.setText(QtGui.QApplication.translate("ManageProjects", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.noteSave.setText(QtGui.QApplication.translate("ManageProjects", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), QtGui.QApplication.translate("ManageProjects", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.linkslist.setSortingEnabled(True)
        self.linkslist.headerItem().setText(0, QtGui.QApplication.translate("ManageProjects", "Link", None, QtGui.QApplication.UnicodeUTF8))
        self.linkslist.headerItem().setText(1, QtGui.QApplication.translate("ManageProjects", "Description", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.linkslist.isSortingEnabled()
        self.linkslist.setSortingEnabled(False)
        self.linkslist.topLevelItem(0).setText(0, QtGui.QApplication.translate("ManageProjects", "google.pl", None, QtGui.QApplication.UnicodeUTF8))
        self.linkslist.topLevelItem(0).setText(1, QtGui.QApplication.translate("ManageProjects", "search engine", None, QtGui.QApplication.UnicodeUTF8))
        self.linkslist.setSortingEnabled(__sortingEnabled)
        self.linkDescGet.setText(QtGui.QApplication.translate("ManageProjects", "Get description", None, QtGui.QApplication.UnicodeUTF8))
        self.linkCreate.setText(QtGui.QApplication.translate("ManageProjects", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.linkDelete.setText(QtGui.QApplication.translate("ManageProjects", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), QtGui.QApplication.translate("ManageProjects", "Links", None, QtGui.QApplication.UnicodeUTF8))
        self.jobslist.setSortingEnabled(True)
        self.jobslist.headerItem().setText(0, QtGui.QApplication.translate("ManageProjects", "Job", None, QtGui.QApplication.UnicodeUTF8))
        self.jobslist.headerItem().setText(1, QtGui.QApplication.translate("ManageProjects", "Deadline", None, QtGui.QApplication.UnicodeUTF8))
        self.jobslist.headerItem().setText(2, QtGui.QApplication.translate("ManageProjects", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.jobslist.headerItem().setText(3, QtGui.QApplication.translate("ManageProjects", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.jobTime.setDisplayFormat(QtGui.QApplication.translate("ManageProjects", "dd-MM-yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.jobStatus.setItemText(0, QtGui.QApplication.translate("ManageProjects", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.jobStatus.setItemText(1, QtGui.QApplication.translate("ManageProjects", "In progress", None, QtGui.QApplication.UnicodeUTF8))
        self.jobStatus.setItemText(2, QtGui.QApplication.translate("ManageProjects", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.jobCreate.setText(QtGui.QApplication.translate("ManageProjects", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEditStatus.setItemText(0, QtGui.QApplication.translate("ManageProjects", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEditStatus.setItemText(1, QtGui.QApplication.translate("ManageProjects", "In progress", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEditStatus.setItemText(2, QtGui.QApplication.translate("ManageProjects", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.jobEdit.setText(QtGui.QApplication.translate("ManageProjects", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.jobDelete.setText(QtGui.QApplication.translate("ManageProjects", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.jobNotes.setItemText(0, QtGui.QApplication.translate("ManageProjects", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.jobAssignNote.setText(QtGui.QApplication.translate("ManageProjects", "Assign Note", None, QtGui.QApplication.UnicodeUTF8))
        self.jobAddToTodays.setText(QtGui.QApplication.translate("ManageProjects", "Add to Todays", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), QtGui.QApplication.translate("ManageProjects", "Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ManageProjects", "Jobs for today", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysJobsList.setSortingEnabled(True)
        self.todaysJobsList.headerItem().setText(0, QtGui.QApplication.translate("ManageProjects", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysJobsList.headerItem().setText(2, QtGui.QApplication.translate("ManageProjects", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysJobsList.headerItem().setText(3, QtGui.QApplication.translate("ManageProjects", "Deadline", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysJobsList.headerItem().setText(4, QtGui.QApplication.translate("ManageProjects", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysNew.setText(QtGui.QApplication.translate("ManageProjects", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysInprogress.setText(QtGui.QApplication.translate("ManageProjects", "In progress", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysDone.setText(QtGui.QApplication.translate("ManageProjects", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.todaysDelete.setText(QtGui.QApplication.translate("ManageProjects", "Delete from list", None, QtGui.QApplication.UnicodeUTF8))
        self.op1.setText(QtGui.QApplication.translate("ManageProjects", "Projects List", None, QtGui.QApplication.UnicodeUTF8))
        self.op2.setText(QtGui.QApplication.translate("ManageProjects", "Tabs", None, QtGui.QApplication.UnicodeUTF8))
        self.op3.setText(QtGui.QApplication.translate("ManageProjects", "Today\'s jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("ManageProjects", "LBPM", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("ManageProjects", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDocument.setTitle(QtGui.QApplication.translate("ManageProjects", "Document", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("ManageProjects", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_collection.setText(QtGui.QApplication.translate("ManageProjects", "Change collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("ManageProjects", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_selected_project.setText(QtGui.QApplication.translate("ManageProjects", "Delete selected project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete_all_projects.setText(QtGui.QApplication.translate("ManageProjects", "Delete all projects", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_new_project.setText(QtGui.QApplication.translate("ManageProjects", "Create new project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_all_project_childs.setText(QtGui.QApplication.translate("ManageProjects", "Clear all project childs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("ManageProjects", "About", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
